# Generated by Django 5.2.6 on 2025-09-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Уникальный email адрес клиента', max_length=255, unique=True, verbose_name='Email адрес')),
                ('full_name', models.CharField(help_text='Полное имя клиента', max_length=200, verbose_name='Ф.И.О.')),
                ('comment', models.TextField(blank=True, help_text='Дополнительная информация о клиенте', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, help_text='Отметка для отключения клиента без удаления', verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'mailing_clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
